# Generated by Django 5.1.6 on 2025-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar_default.svg', null=True, upload_to='avatars/'),
        ),
    ]
